### PR TITLE
Add bounding box test programs

### PR DESCRIPTION
**Pull request by liu2g**

### CODE REVIEW

**Comment by tjunruh** [comment]
I ran the application to generate a table, and it took significantly longer to complete on this pull request than on main. The reason is that the model and label binarizer are loaded every time the get_letters function is run. This is not necessary since they are loaded in the get_predictions_function. Could you remove self.__LB = self.file_manager_operative.load_LabelBinarizer() and self.__model = self.file_manager_operative.load_ocr_model() from predict.py?

**Comment by tjunruh** [comment]
For testing, the model and labelbinarizer should probably be loaded within the testing files rather than relying on get_letters to load them. Maybe, a separate, duplicate function of get_letters should be used. Then the get_letters function in predict.py can be made private again with two underscores.

**Comment by liu2g** [comment]
With all available data,

Vanilla method
```
┌───────────┬──────────┐
│ Precision │ 0.963135 │
├───────────┼──────────┤
│ Recall    │ 0.904695 │
├───────────┼──────────┤
│ F1 Score  │ 0.933001 │
└───────────┴──────────┘
```
Updated connected component method
```
┌───────────┬──────────┐
│ Precision │ 0.954915 │
├───────────┼──────────┤
│ Recall    │ 0.95149  │
├───────────┼──────────┤
│ F1 Score  │ 0.953199 │
└───────────┴──────────┘
```
(Liu's) XY split method
```
┌───────────┬──────────┐
│ Precision │ 0.941904 │
├───────────┼──────────┤
│ Recall    │ 0.938231 │
├───────────┼──────────┤
│ F1 Score  │ 0.940064 │
└───────────┴──────────┘
```

**Comment by liu2g** [comment]
```bash
find ~/Datasets/bboxtestimg/* -type d | xargs -tL1 ./vanilla.py
find ~/Datasets/bboxtestimg/* -type d | xargs -tL1 ./conncomp-btrmorph.py
find ~/Datasets/bboxtestimg/* -type d | xargs -tL1 ./xysplit.py
```
The above lines finds all subdirs under `Datasets/bboxtestimg` and pipe it into the programs one line after another by `xargs`.
`-t` flag prints the command it expands in the end before executing.
`-L1` flag makes sure the lines run one after another sequentially

```bash
find ~/Datasets/bboxtestimg -name "Vanilla_*.csv" | xargs ../tools/bboxbenchmark.py
find ~/Datasets/bboxtestimg -name "ConnCompBtrMorph_*.csv" | xargs ../tools/bboxbenchmark.py
find ~/Datasets/bboxtestimg -name "XYsplit_*.csv" | xargs ../tools/bboxbenchmark.py
```
The above lines recursively finds all files by the patterns, which is obvious by the result.csv naming scheme.
Similarly, the file paths goes into the benchmark program with `xargs`, except they go all into as N arguments.
The benchmark program by design accepts infinite arguments and include all numbers in its report and therefore `-L1` is not used

**Review by tjunruh — APPROVED** [review]

**Pull request merged**
